let databaseArray = [
  {
    Title: "Beguiling 22 Karat Yellow Gold Overlapping Bell Jhumkas",
    Description:
      "Enchanting 22 Karat yellow gold jhumkas with a textured circular base, holding a textured bell bead trail, adorned with 2 ball hangings at the bottom",
    Type: "Jhumka",
    Weight: "5.580g",
    Price: 36137.0,
    DiscountPrice: 36000.0,
    Img: ["../img/bot1.jpg", "../img/bottle.jpeg"],
    Brand: "Contingo",
  },
  {
    Title: "Hidrate Spark PRO Smart Water Bottle",
    Description:
      "Hidrate Spark PRO Smart Water Bottle – Insulated Stainless Steel – Tracks Water Intake with Bluetooth, LED Glow Reminder When You Need to Drink – Straw Lid, 21 oz",
    Type: "Jhumka",
    Weight: "3.112g",
    Price: 45206.0,
    DiscountPrice: 45000.0,
    Img: [
      "../img/bot2.jpg",
      "../img/bot22.jpg",
      "../img/bot23.jpg",
      "../img/bot24.jpg",
    ],
    Brand: "Tanishq",
  },
  {
    Title: "Radiant Traditional Jhumkas",
    Description:
      "Hidrate Spark PRO Smart Water Bottle – Insulated Stainless Steel – Tracks Water Intake with Bluetooth, LED Glow Reminder When You Need to Drink – Straw Lid, 21 oz",
    Type: "Jhumka",
    Weight: "6.706g",
    Price: 43700.0,
    DiscountPrice: 43000.0,
    Img: ["../img/bot42.webp"],
    Brand: "Tanishq",
  },
  {
    Title: "Artistic Yellow Gold Tiered Floral Jhumkas",
    Description:
      "These radiant 22 Karat Gold Jhumkas feature a floral stud with angled petals suspending 2 bells with etched matte panels, ending in a long gold bead",
    Type: "Jhumka",
    Weight: "6.564g",
    Price: 44819.0,
    DiscountPrice: 44000.0,
    Img: [
      "../img/bot3.jpg",
      "../img/bot19.jpg",
      "../img/bot20.jpg",
      "../img/bot21.jpg",
    ],
    Brand: "Tanishq",
  },
  {
    Title: "Delightful Yellow Gold Clover Jhumkas",
    Description:
      "These lovely 22 Karat Gold Jhumkas feature an etched, matte 3-petal stud suspending a bell with matte drops, roped frets and gold discs ending in a bead",
    Type: "Jhumka",
    Weight: "6.764g",
    Price: 20718.0,
    DiscountPrice: 20000.0,
    Img: ["../img/bot4.jpg", "../img/bot18.jpg"],
    Brand: "Tanishq",
  },
  {
    Title: "Traditional Yellow Gold Filigree Jhumkas",
    Description:
      "These classic 22 Karat Gold Jhumkas feature a teardrop stud lined with small discs suspending a filigree bell ending with roped rings and hanging beads",
    Type: "Jhumka",
    Weight: "8.232g",
    Price: 55017.0,
    DiscountPrice: 55000.0,
    Img: ["../img/bot5.jpg", "../img/bot17.jpg"],
    Brand: "Tanishq",
  },
  {
    Title: "Incandescent Yellow Gold Swan Jhumkas",
    Description:
      "These graceful 22 Karat yellow Gold Jhumkas feature a paisley lined filigree bell crowned by 2 carved swans and a roped disc suspended by a floral stud",
    Type: "Jhumka",
    Weight: "3.674g",
    Price: 24555.0,
    DiscountPrice: 24000.0,
    Img: ["../img/bot6.jpg", "../img/bot16.jpg"],
    Brand: "Tanishq",
  },
  {
    Title: "Avant-Garde Yellow Gold Carved Jhumkas",
    Description:
      "These grand 22 Karat Gold Jhumkas feature a carved stud shaped like an elongated mitre, suspending a waved bell with cutout bands ending in a teardrop",
    Type: "Jhumka",
    Weight: "4.728g",
    Price: 31476.0,
    DiscountPrice: 30000.0,
    Img: ["../img/bot7.jpg", "../img/bot14.jpg", "../img/bot15.jpg"],
    Brand: "Tanishq",
  },
  {
    Title: "Brilliant Yellow Gold Peacock Jhumkas",
    Description:
      "These grand 22 Karat Gold Jhumkas feature a carved peacock stud suspending a lantern-like bell adorned with cutout diamonds and discs, ending in a bead",
    Type: "Jhumka",
    Weight: "3.660g",
    Price: 24461.0,
    DiscountPrice: 24000.0,
    Img: ["../img/bot8.jpg", "../img/bot9.jpg"],
    Brand: "Tanishq",
  },
  {
    Title: "Splendid Gold Jhumka Earrings",
    Description:
      "Illuminate your occasion ensemble by pairing it with these Captivating Jhumka Earrings crafted in 22 Karat High Polish Yellow Gold.",
    Type: "Jhumka",
    Weight: "4.273g",
    Price: 27672.0,
    DiscountPrice: 27000.0,
    Img: ["../img/bot10.jpg"],
    Brand: "Tanishq",
  },
  {
    Title: "Enchanting 18 Karat Yellow Gold And Pearl Geometric Drop Earrings",
    Description:
      "These quirky 18 Karat yellow gold earrings feature a geometric design with a pearl adorned at the centre and at the bottom",
    Type: "Drops",
    Weight: "3.021g",
    Price: 15673.0,
    DiscountPrice: 15000.0,
    Img: ["../img/bot11.jpg", "../img/bot12.jpg", "../img/bot13.jpg"],
    Brand: "Tanishq",
  },
  {
    Title: "Traditional 22 Karat Gold And Multi Stone Drop Earrings",
    Description:
      "These traditional 22 Karat gold drops feature a stone-set gold bead encrusted crown suspending a studded, beaded triangle with hanging ball charms",
    Type: "Drops",
    Weight: "10.445g",
    Price: 66874.0,
    DiscountPrice: 66000.0,
    Img: ["../img/bot26.jpg", "../img/bot27.jpg"],
    Brand: "Tanishq",
  },
  {
    Title: "Exquisite 18 Karat Yellow Gold And Citrine Drops",
    Description:
      "A citrine stone is prong-set on a gold drop that's suspended by an O-ring from an inverted V post featuring jali work in these 18 Karat gold drops",
    Type: "Drops",
    Weight: "5.059g",
    Price: 26015.0,
    DiscountPrice: 25000.0,
    Img: ["../img/bot28.jpg", "../img/bot29.jpg", "../img/bot30.jpg"],
    Brand: "Tanishq",
  },
  {
    Title: "Alluring 22 Karat Gold And Ruby Floral Drop Earrings",
    Description:
      "These luxurious 22 Karat gold drops feature shimmering prong-set rubies in 2 burgeoning floral clusters, attached to a screw-back post fastening",
    Type: "Drops",
    Weight: "7.701g",
    Price: 54136.0,
    DiscountPrice: 53000.0,
    Img: ["../img/bot31.jpg", "../img/bot32.jpg"],
    Brand: "Tanishq",
  },
  {
    Title: "Nimaya Ruby Drop Earrings",
    Description:
      "Ruby Drop Earrings with Traditional Design crafted in 22 Karat Yellow Gold with glossy finish",
    Type: "Drops",
    Weight: "6.610g",
    Price: 47880.0,
    DiscountPrice: 46000.0,
    Img: ["../img/bot33.jpg", "../img/bot34.jpg"],
    Brand: "Tanishq",
  },
  {
    Title: "Eccentric 22 Karat Gold And Ruby Drop Earrings",
    Description:
      "These quirky 22 Karat gold drops features a hanging teardrop ruby suspended from 2 clusters of rubies attached to each other by 3 arcs of gold",
    Type: "Drops",
    Weight: "5.636g",
    Price: 38982.0,
    DiscountPrice: 37000.0,
    Img: ["../img/bot35.jpg", "../img/bot36.jpg"],
    Brand: "Tanishq",
  },
  {
    Title: "Enthralling 22 Karat Gold And Ruby Floral Drop Earrings",
    Description:
      "These gorgeous 22 Karat gold drops feature prong-set rubies arranged in a floral design, with a delicate hanging teardrop ruby suspended by o-ring",
    Type: "Drops",
    Weight: "7.516g",
    Price: 54530.0,
    DiscountPrice: 53000.0,
    Img: ["../img/bot37.jpg", "../img/bot38.jpg"],
    Brand: "Tanishq",
  },
  {
    Title: "Enrapturing 22 Karat Gold And Multi Stone Teardrop Earrings",
    Description:
      "These lovely 22 Karat gold drops feature 1 teardrop ruby set amidst round emeralds, and another hanging from an emerald nestled between 2 more rubies",
    Type: "Drops",
    Weight: "5.061g",
    Price: 35895.0,
    DiscountPrice: 35000.0,
    Img: ["../img/bot39.jpg", "../img/bot40.jpg"],
    Brand: "Tanishq",
  },
  {
    Title: "Graceful 22 Karat Yellow Gold Lead Patterned Drop Earrings",
    Description:
      "These oh-so-lovely 22 Karat yellow gold earrings feature a long chain accented with Ruby studded leaves",
    Type: "Drops",
    Weight: "3.106g",
    Price: 23533.0,
    DiscountPrice: 23000.0,
    Img: [
      "../img/bot41.jpg",
      "../img/bot42.webp",
      "../img/Kiyo-UVC-Bottle-500ml-Blue-Hour_900x.webp",
    ],
    Brand: "Tanishq",
  },
  {
    Title: "Graceful 22 Karat Gold And Ruby Floral Drop Earrings",
    Description:
      "These lush 22 Karat gold drops feature 11 dazzling rubies in a floral design with 1 delicate ruby teardrop suspended from the tip of the flower",
    Type: "Drops",
    Weight: "3.116g",
    Price: 22913.0,
    DiscountPrice: 22000.0,
    Img: ["../img/bot43.jpg", "../img/bot43A.jpg", "../img/bot44.jpg"],
    Brand: "Tanishq",
  },
  {
    Title: "Luxurious 18 Karat Gold And Ruby Curved Stud",
    Description:
      "This luxurious pair of earrings feature 4 ruby-studs in a floral design attached to an 18 Karat gold stem with leaf detailing, truly setting it apart",
    Type: "Hoops",
    Weight: "3.610g",
    Price: 20997.0,
    DiscountPrice: 19000.0,
    Img: ["../img/bot35A.jpg", "../img/bot35B.jpg", "../img/bot35.jpg"],
    Brand: "Tanishq",
  },
  {
    Title: "Dainty Beaded Gold Hoop Earrings",
    Description:
      "Add the classic sheen of gold to your outfit and look stunning with this pair of hoop earrings crafted in 18 Karat Yellow Gold.",
    Type: "Hoops",
    Weight: "1.266g",
    Price: 6976.0,
    DiscountPrice: 6000.0,
    Img: ["../img/bott2.jpg", "../img/bott5.jpg", "../img/bott33.jpg"],
    Brand: "Tanishq",
  },
  {
    Title: "Sublime Gold Hoop Earrings",
    Description:
      "Add charm to your everyday look with this sublime pair of gold hoops crafted in 18 Karat Yellow Gold.",
    Type: "Hoops",
    Weight: "0.545g",
    Price: 2899.0,
    DiscountPrice: 2700.0,
    Img: ["../img/bott45.jpg", "../img/bot50.jpg"],
    Brand: "Tanishq",
  },
  {
    Title: "Dainty Delicate Gold Hoop Bottles",
    Description:
      "Make a subtle style statement with these delicate hoop earrings crafted in 18 Karat Yellow Gold with a glossy finish.",
    Type: "Hoops",
    Weight: "1.286g",
    Price: 6760.0,
    DiscountPrice: 6700.0,
    Img: ["../img/bot10.jpg", "../img/bot11.jpg", "../img/bot12.jpg"],
    Brand: "Tanishq",
  },
  {
    Title: "Timeless 18 Karat Yellow Gold Bali-Style Hoop Earrings",
    Description:
      "These 18 Karat gold earrings feature two rings and a multi-faceted gold bead with tiny dots all over it strung on a smooth, easy-on-hinged gold hoop",
    Type: "Hoops",
    Weight: "0.966g",
    Price: 5139.0,
    DiscountPrice: 5000.0,
    Img: ["../img/bot13.jpg", "../img/bot14.jpg"],
    Brand: "Tanishq",
  },
  {
    Title: "Delightful Gold Hoop Earrings",
    Description:
      "Add a touch of glam to your sublime look with these Geometric Hoop Earrings Crafted in 22 Karat High Polish Yellow Gold suitable for any occasion.",
    Type: "Hoops",
    Weight: "4.077g",
    Price: 23868.0,
    DiscountPrice: 22000.0,
    Img: ["../img/bot15.jpg", "../img/bot16.jpg"],
    Brand: "Tanishq",
  },
  {
    Title: "Entrancing Swirling Gold Beaded Hoop Bali Earrings",
    Description:
      "The mesmerising swirling mesh pattern in these floral hoop earrings crafted in 18 Karat Yellow Gold makes this an enchanting pair.",
    Type: "Hoops",
    Weight: "3.608g",
    Price: 20035.0,
    DiscountPrice: 19000.0,
    Img: ["../img/bot17.jpg", "../img/bot18.jpg", "../img/bot19.jpg"],
    Brand: "Tanishq",
  },
  {
    Title: "Elegant Gold Hoop Bali Earrings",
    Description:
      "Revel in Minimalistic glory with these Hoop Earrings Crafted in 22 Karat Glossy Yellow Gold. Comes in a fine glossy finish.",
    Type: "Hoops",
    Weight: "5.66g",
    Price: 33171.0,
    DiscountPrice: 32000.0,
    Img: [
      "../img/bot20.jpg",
      "../img/bot22.jpg",
      "../img/bot24.jpg",
      "../img/bot24.jpg",
    ],
    Brand: "Tanishq",
  },
  {
    Title: "Romantic Gold Hoop Earrings",
    Description:
      "Romanticise every moment of your life with the subtle sheen of these hoop earrings crafted in 18 Karat Yellow Gold.",
    Type: "Hoops",
    Weight: "1.597g",
    Price: 8496.0,
    DiscountPrice: 8000.0,
    Img: ["../img/bot27.jpg", "../img/bot28.jpg", "../img/bot29.jpg"],
    Brand: "Tanishq",
  },
  {
    Title: "Sophisticated Yellow Gold Thunderbolt Hoop Bottle",
    Description:
      "These suave 18 Karat Yellow Gold Hoops feature a polished 3-pronged zigzag with a hanging teardrop, suspended by o-ring from a flattened hook",
    Type: "Hoops",
    Weight: "3.466g",
    Price: 19100.0,
    DiscountPrice: 18000.0,
    Img: ["../img/bot30.jpg", "../img/bot31.jpg"],
    Brand: "Contigo",
  },
  {
    Title: "Contigo Ashland Chill 24oz Stainless Steel Water Bottle",
    Description:
      "Contigo Ashland Chill 24oz Stainless Steel Water Bottle with Leakproof Lid & Straw, Smart Temperature Technology Keeps Beverages Hot and cold water.",
    Type: "Studs",
    Weight: "8.921g",
    Price: 63040.0,
    DiscountPrice: 62000.0,
    Img: ["../img/contigo.jpg", "../img/contigo.jpg"],
    Brand: "Contigo",
  },
  {
    Title: "Charming 22 Karat Yellow Gold And Ruby Floral Stud Bottle",
    Description:
      "These riveting 22 Karat gold studs feature 4 oval and 5 round prong-set rubies arranged in a charmingly classic flower design, with a screw-back post",
    Type: "Studs",
    Weight: "5.096g",
    Price: 37106.0,
    DiscountPrice: 36000.0,
    Img: ["../img/bot1.jpg", "../img/bot2.jpg"],
    Brand: "Tanishq",
  },
  {
    Title: "Charming 18 Karat Yellow Gold And Pearl Stud Bottle",
    Description:
      "Graceful 18 Karat yellow gold studs featuring 3 stems flaunting a swirl pattern and holding a pearl at the bottom",
    Type: "Studs",
    Weight: "2.356g",
    Price: 11700.0,
    DiscountPrice: 11000.0,
    Img: ["../img/bot10.jpg", "../img/bot3.jpg", "../img/bot20.jpgs"],
    Brand: "Tanishq",
  },
  {
    Title: "Resplendent Floral Ruby Stud Earrings",
    Description:
      "Floral Stud Earrings set in 22 Karat Yellow Gold and studded with Marquise and Round Rubies",
    Type: "Studs",
    Weight: "5.942g",
    Price: 42912.0,
    DiscountPrice: 42000.0,
    Img: ["../img/bot12.jpg", "../img/bot11.jpg"],
    Brand: "Tanishq",
  },
  {
    Title: "Mesmerizing 22 Karat Gold And Ruby Bloom Stud Earrings",
    Description:
      "These glamorous 22 Karat gold studs feature 9 lush prong-set marquise rubies tipped in gold, encircling 1 round ruby in a blooming flower design",
    Type: "Studs",
    Weight: "4.117g",
    Price: 29012.0,
    DiscountPrice: 28000.0,
    Img: ["../img/bot15.jpg", "../img/bot5.jpg"],
    Brand: "Tanishq",
  },
  {
    Title:
      "Appealing 18 Karat Yellow Gold Ruby-Embellished Petals Stud Earrings",
    Description:
      "Awe-striking 18 Karat yellow gold studs featuring a flower design with 6 petals and a bud, all embellished with Rubies",
    Type: "Studs",
    Weight: "1.693g",
    Price: 11160.0,
    DiscountPrice: 11000.0,
    Img: ["../img/bot4.jpg", "../img/bot14.jpg"],
    Brand: "Tanishq",
  },
  {
    Title: "Minimalist 18 Karat Yellow Gold And Pearl Studs",
    Description:
      "A true mark of understated elegance, these 18 Karat gold studs feature a luminous pearl attached to the gold post and a Bombay screw back",
    Type: "Studs",
    Weight: "1.693g",
    Price: 9348.0,
    DiscountPrice: 9000.0,
    Img: ["../img/bot16.jpg", "../img/bot26.jpg", "../img/bot30.jpg"],
    Brand: "Tanishq",
  },
  {
    Title:
      "Classy 18 Karat Yellow Gold And Pearl Swirling Petals Stud Earrings",
    Description:
      "Impressive 18 Karat yellow gold studs featuring a flower design with swirling petals and a pearl-adorned bud",
    Type: "Studs",
    Weight: "5.449g",
    Price: 24247.0,
    DiscountPrice: 24000.0,
    Img: ["../img/bot30.jpg", "../img/bot31.jpg"],
    Brand: "Tanishq",
  },
  {
    Title: "Resplendent Floral Ruby Stud Earrings",
    Description:
      "Floral Stud Bottle set in 22 Karat Yellow Gold and studded with Marquise and Round Rubies",
    Type: "Studs",
    Weight: "5.942g",
    Price: 42912.0,
    DiscountPrice: 42000.0,
    Img: ["../img/bot32.jpg", "../img/bot33.jpg"],
    Brand: "Tanishq",
  },
  {
    Title: "Opulent 18 Karat Gold And Emerald Paisley Drop Earrings",
    Description:
      "These 18 Karat gold drop earrings feature lush emeralds clustered in a twisted paisley motif, with a single dangling emerald teardrop",
    Type: "Studs",
    Weight: "5.611g",
    Price: 38081.0,
    DiscountPrice: 37000.0,
    Img: ["../img/bot34.jpg", "../img/bot35.jpg"],
  },
];

localStorage.setItem("database", JSON.stringify(databaseArray));
